title: Lenovo HPC
email: hpchelp@lenovo.com
description: >
  Lenovo HPC resources, news, and documentation
baseurl: /users
markdown: kramdown

kramdown:
        input: GFM
        hard_wrap: false
        syntax_highlighter: rouge
        syntax_highlighter_opts:
                default_lang: 'sh'

