#!/usr/bin/python
import os
import sys
path = os.path.dirname(os.path.realpath(__file__))
path = os.path.realpath(os.path.join(path, '..', 'confluent', 'confluent_server'))
sys.path.append(path)


import confluent.config.attributes as attr
import shutil

shutil.copyfile('_special/nodeattribtmpl.md', 'docs/attribs.md')
outf = open('docs/attribs.md', 'a')
for field in sorted(attr.node):
    outf.write('\n{0}\n: {1}\n'.format(field, attr.node[field]['description']))

